### ISSUE TITLE
Issue: Visual hitbox don't match with the actual hitbox

### ISSUE THREAD

**Issue by LikiaBili** [peppy/ruleset-typer#2]
like i compiled the ruleset, and when i hit the hitobject at the exactly point that perfectly aligns with the hitbox, it just counts me as a miss.
when i press early, it shows i'm pretty accurate on the display

**Comment by LikiaBili** [comment]
https://github.com/peppy/ruleset-typer/assets/103659676/0011b08f-dd7e-4e7a-8226-7e1404f8e8f1

**Comment by CloneWith** [comment]
It turns out to be an issue with the playfield, see 

https://github.com/peppy/ruleset-typer/blob/f951b13e5bef6c8c76eeafed2b961dffa8ff4af1/osu.Game.Rulesets.Typer/UI/TyperPlayfield.cs#L15-L39

Tuning the Padding might work.
